# Generated by Django 4.1 on 2024-04-18 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='funkos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funko_api.funko'),
        ),
    ]
