# Generated by Django 4.1 on 2024-04-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0002_alter_user_funkos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='funkos',
        ),
        migrations.AddField(
            model_name='user',
            name='funkos',
            field=models.ManyToManyField(to='funko_api.funko'),
        ),
    ]
