# Generated by Django 4.1 on 2024-05-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='nivel',
            new_name='level',
        ),
    ]
